#
# Executes commands at the start of an interactive session.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#
# Source Prezto.
if [[ -s "${ZDOTDIR:-$HOME}/.zprezto/init.zsh" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprezto/init.zsh"
fi

# Customize to your needs...

export PATH=/usr/local/bin:/usr/local/sbin:/usr/bin:/bin:/usr/sbin:/sbin

export PATH="$HOME/.yarn/bin:$PATH"

export PATH="$HOME/anaconda3/bin:$PATH"
# tabtab source for serverless package
# uninstall by removing these lines or running `tabtab uninstall serverless`
[[ -f /Users/marciaga/.config/yarn/global/node_modules/tabtab/.completions/serverless.zsh ]] && . /Users/marciaga/.config/yarn/global/node_modules/tabtab/.completions/serverless.zsh
# tabtab source for sls package
# uninstall by removing these lines or running `tabtab uninstall sls`
[[ -f /Users/marciaga/.config/yarn/global/node_modules/tabtab/.completions/sls.zsh ]] && . /Users/marciaga/.config/yarn/global/node_modules/tabtab/.completions/sls.zsh
export PATH="/usr/local/opt/ruby/bin:$PATH"
